AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/handler/hello-world
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/handler/greeting
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /greeting
            Method: post

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${PREFIX}-url-${PROJECT}
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  URLCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/create
      Runtime: go1.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable

  URLResolve:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/resolve
      Runtime: go1.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDBTable
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable

Parameters:
  PREFIX:
    Type: String
  PROJECT:
    Type: String

Outputs:
  PREFIX:
    Value: !Ref PREFIX
  PROJECT:
    Value: !Ref PROJECT
  Endpoint:
    Description: "API Gateway endpoint URL for for Example Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"