AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${PROJECT}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      StageName: v1

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Timeout: 180
      Handler: dist/handler/example
      Environment:
        Variables:
          PREFIX: !Ref PREFIX
          PROJECT: !Ref PROJECT
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/handler/hello-world
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref API
  GreetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: dist/handler/greeting
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /greeting
            Method: post
            RestApiId: !Ref API

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join [ -, [ !Ref PREFIX, url, !Ref PROJECT ] ]
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PreviewTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Join [ -, [ !Ref PREFIX, preview, !Ref PROJECT ] ]
      KeySchema:
        - AttributeName: url
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S

  URLCreate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/create
      Runtime: go1.x
      Policies:
        - Version: '2012-10-17' # Allow write access to DynamoDB table
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt DynamoDBTable.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref API
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable

  URLResolve:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/resolve
      Runtime: go1.x
      Policies:
        - Version: '2012-10-17' # Allow read access to DynamoDB table
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt DynamoDBTable.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
            RestApiId: !Ref API
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTable
      Tracing: Active

  PreviewGenerate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler/preview
      Runtime: go1.x
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt PreviewTable.Arn
      Events:
        DynamoDBEvent:
          Type: DynamoDB
          Properties:
            Stream:
              !GetAtt DynamoDBTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 10
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref PreviewTable
      Tracing: Active

Parameters:
  PREFIX:
    Type: String
  PROJECT:
    Type: String

Outputs:
  PREFIX:
    Value: !Ref PREFIX
  PROJECT:
    Value: !Ref PROJECT
  HelloEndpoint:
    Description: "API Gateway endpoint URL for for Example Function"
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/v1/hello"
  GreetingEndpoint:
    Description: "API Gateway endpoint URL for for Greeting Function"
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/v1/greeting"
  URLShortenerEndpoint:
    Description: "API Gateway endpoint URL for for Greeting Function"
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/v1/"